owner: navikt
repos:
  - reponame:
      - esyfo-cli
  - reponame:
      - aktivitetskrav-frontend
      - dialogmote-frontend
      - meroppfolging-frontend
      - oppfolgingsplan-frontend
    checks:
      - next-app / Build for dev
      - next-app / Test and lint
  - reponame:
      - aktivitetskrav-mikrofrontend
      - dialogmote-mikrofrontend
    checks:
      - vite-mikrofrontend / build
  - reponame:
      - esyfo-proxy
    checks:
      - build and push
  - reponame:
      - esyfovarsel
      - lps-oppfolgingsplan-mottak
      - syfobrukertilgang
      - syfomotebehov
      - syfooppfolgingsplanservice
    checks:
      - jar-app / Test
      - jar-app / Build
  - reponame:
      - aktivitetskrav-backend
      - meroppfolging-backend
      - oppfolgingsplan-backend
    checks:
      - boot-jar-app / Test
      - boot-jar-app / Build

