owner: navikt
repos:
  - reponame:
      - esyfo-cli
  - reponame:
      - dialogmote-frontend
      - meroppfolging-frontend
    checks:
      - next-app / Build for dev
      - next-app / Test and lint
